### PR TITLE
Fix/styling fixes

### LINKED ISSUE #222: Box office page is hard to use on mobile
used the phone box office page during mtb to speed up ticketing - the check in all tickets button was kinda hard to click, and we clicked it unintentionally a few times - needs a bit of looking at!

### LINKED ISSUE #224: dodgy boxes on admin panel
when rescaling window

image

### PR DESCRIPTION
**Pull request by streth11**
closes #224 
closes #222 

also neatens the new box office banner

### CODE REVIEW

File: components/box-office/BookingDetailsRow.vue [hunk 1]
```diff
@@ -50,7 +50,45 @@
             </button>
           </template>
         </div>
-        <div class="flex-grow order-1 overflow-x-auto">
+        <!-- Mobile -->
+        <div class="sm:hidden">
```
Comment (atoff) [inline components/box-office/BookingDetailsRow.vue:54]: Can we some how merge mobile with no mobile to prevent duplication like this?

**Review by atoff — CHANGES_REQUESTED** [review]

**Review by atoff — APPROVED** [review]
