### PR TITLE
fix: Fix Production Permission Assigner Fatal Errors

### LINKED ISSUE #659: Changing an existing user's permissions in the production permissions assigner leads to an error
Error is: `TypeError: can't define property "modified": Object is not extensible`

### PR DESCRIPTION
**Pull request by HappyNTH**
Resolves #659. Also introduces a test to make sure the page is functioning properly in the future.

### CODE REVIEW

File: pages/administration/productions/[productionSlug]/permissions.vue [hunk 1]
```diff
@@ -20,120 +21,144 @@
...
+
+    const production = data.production;
+
+    if (!production) {
+      throw createSafeError({
+        statusCode: 404,
+        message: 'This production does not exist'
+      });
+    }
+    if (production.assignedUsers === null) {
```
Comment (zst-c) [inline pages/administration/productions/[productionSlug]/permissions.vue:59]: How does this query check for perms? Does `production.assignedUsers` only return data if the requesting user has perms?

**Review by zst-c — APPROVED** [review]
All seems good to me!

File: pages/administration/productions/[productionSlug]/permissions.vue (hunk 1 above)
Comment (HappyNTH) [reply pages/administration/productions/[productionSlug]/permissions.vue:59]: Yes, this is handled on the API side, which will only return data that a user has permission to view. It may be, therefore, that a user has permission to view a production, but not permission to edit assigned users, in which case they will recieve a partial response from the API wherein `production.assignedUsers` is null
