### PR TITLE
fix: Adds an error message when a user attempts to change their email to one already in-use (resolves #201)

### LINKED ISSUE #201: Changing email when already used
When attempting to change email from within the user details editor to an email used by someone else, validation errors from the mutation are not shown

### PR DESCRIPTION
**Pull request by HappyNTH**
Also:
- Fixes a typo that prevented the support email appearing after `Want to delete your account? Get in touch at` when editing your user details
- Adds placeholder field text to the `ChangeEmail` and `ChangePassword` componenets, to make them a bit easier to navigate

### CODE REVIEW

File: components/user/ChangeEmail.vue [hunk 1]
```diff
@@ -7,21 +7,28 @@
...
+          placeholder="Password"
           :errors="errors"
           required
         />
+        <div
+          v-if="errors && errors.has('email')"
+          class="text-sta-rouge text-sm font-semibold"
+        >
+          <p>Error: {{ errors.first('email').message }}</p>
+        </div>
```
Comment (atoff) [inline components/user/ChangeEmail.vue:31]: This should be automatically handled by the `text-input` component - check out https://github.com/BristolSTA/uobtheatre-web/blob/develop/components/ui/Input/UiInputText.vue. I think you just need to specify `error-key` attribute on each of them

File: components/user/ChangeEmail.vue [hunk 2]
```diff
@@ -7,21 +7,28 @@
         class="flex flex-col p-6 pt-0 space-y-2"
         @submit.prevent="addNewEmail"
       >
-        Enter the new email you wish to switch to, and your password.
         <text-input
           v-model="email"
           name="New Email"
```
Comment (atoff) [inline components/user/ChangeEmail.vue:12]: So fun fact, I changed this component fairly significantly a while back, where I removed a label that was bundled inside the `text-input` component. I have clearly missed a lot of cases where we used this functionality!
We can remove the `name` attribute from this (and password below), as they were only used to automatically display a level for the text input. 

If you wanted to re-instate the label (vs a placeholder, which I am absolutely fine with btw!), you just need to wrap inside a `UiFormLabel` component (e.g. https://github.com/BristolSTA/uobtheatre-web/blob/develop/components/auth/AuthBox.vue#L50)

**Review by atoff — CHANGES_REQUESTED** [review]

File: components/user/ChangeEmail.vue (hunk 2 above)
Comment (HappyNTH) [reply components/user/ChangeEmail.vue:12]: I'm pretty torn! Placeholders have a certain elegance:

image

Whereas labels maybe feel a bit more divided up?

image

I'm honestly leaning towards placeholders myself, but if you think strongly otherwise that's fine too haha

Comment (streth11) [reply components/user/ChangeEmail.vue:12]: i like the placeholders more

File: components/user/ChangeEmail.vue [hunk 3]
```diff
@@ -4,22 +4,25 @@
...
+          error-key="email"
           required
         />
         <text-input
           v-model="password"
           name="Password"
           type="password"
+          placeholder="Password"
           :errors="errors"
+          error-key="email"
```
Comment (atoff) [inline components/user/ChangeEmail.vue:25]:
```suggestion
          error-key="password"
```
?

**Review by atoff — APPROVED** [review]
🚀
