### PR TITLE
fix/not auto check-in box office sold ticket

### LINKED ISSUE #254: Don't always auto check in box office sold ticket
Scenario: User purchases tickets in person at box office location for a performance at a different time. At the moment, any tickets sold through box office interface are automatically checked in, and so when they come to collect at the other performance they looked to already be collected

Fix: we should change the logic so it only checks in if the performance doors have opened (e.g. doorsTime minus 5 mins is in the past)

### PR DESCRIPTION
**Pull request by streth11**
closes #254

### CODE REVIEW

File: pages/box-office/_performanceId/sell/complete.vue [hunk 1]
```diff
@@ -8,14 +8,28 @@
...
+      <div>
+        <button
+          v-if="!checkedIn"
+          class="btn btn-green font-semibold animate-pulse animate w-30"
+          @click="checkInTickets()"
+          @keypress="checkInTickets()"
+        >
+          Check In Tickets
+        </button>
+        <button v-if="checkedIn" class="btn btn-outline disabled w-30" disabled>
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:21]:
```suggestion
        <button v-else class="btn btn-outline disabled w-30" disabled>
```

**Review by atoff — CHANGES_REQUESTED** [review]
Nothing wrong with the work done here, but not quite what I was imagining.

I was thinking we would auto-check in tickets purchased this way under certain conditions (i.e. from doorsOpen - 15 mins to performance finishes). Outside of these times, we wouldn't automatically check in the tickets.

Equally, prehaps when we have checked in the tickets (either automatically or not), maybe we should offer the option to un-check them?

File: pages/box-office/_performanceId/sell/complete.vue [hunk 2]
```diff
@@ -34,41 +58,96 @@ export default {
...
+        successToast.fire({
+          timer: 4000,
+          title: 'Tickets un-checked in',
+        })
+      } catch (e) {
+        errorToast.fire({
+          title: 'Unable to un-check in tickets',
+        })
+      }
+    },
```
Comment (streth11) [inline pages/box-office/_performanceId/sell/complete.vue:150]: on uncheck in console errors with `data[mutationName] is undefined`

File: pages/box-office/_performanceId/sell/complete.vue [hunk 3]
```diff
@@ -51,10 +61,25 @@ export default {
...
+    performanceDoorsDiffMinutes() {
+      return (
+        (Date.parse(this.booking.performance.doorsOpen) - this.currentTime) /
+        60000
+      )
+    },
+    autoCheckIn() {
+      // Performance doors are opening within 15 minutes
+      return this.performanceDoorsDiffMinutes <= 15
+    },
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:77]: I'd be tempted to move `autoCheckIn` from a computed variable to a method (e.g. `canAutoCheckIn()`). This would result in not needing to have both of the newly computed variables you introduced. 

It also avoids a potential issue caused by `currentTime` being static (it is set in the data when you load the page, so currentTime is actually just the time you opened the page. If they stay here for long enough the difference between the actual time and your `currentTime` could be long enough to cause an issue)

Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:77]: I'd be tempted to move `autoCheckIn` from a computed variable to a method (e.g. `canAutoCheckIn()`). This would result in not needing to have both of the newly computed variables you introduced. In theory we only need to use computed variables when we are referencing them somewhere dynamically (like showing them on a page) - as we only call from another function we can make it a function.

It also avoids a potential issue caused by `currentTime` being static (it is set in the data when you load the page, so currentTime is actually just the time you opened the page. If they stay here for long enough the difference between the actual time and your `currentTime` could be long enough to cause an issue)

File: pages/box-office/_performanceId/sell/complete.vue [hunk 4]
```diff
@@ -51,10 +61,25 @@ export default {
   data() {
     return {
       checkedIn: false,
+      currentTime: new Date(),
     }
   },
+  computed: {
+    performanceDoorsDiffMinutes() {
+      return (
+        (Date.parse(this.booking.performance.doorsOpen) - this.currentTime) /
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:70]: Could use the Luxon DateTime library here (already installed) - take a look at https://github.com/BristolSTA/uobtheatre-web/blob/develop/pages/publicity-screen/_venueSlugs/index.vue#L146 and https://moment.github.io/luxon/#/math?id=diffs

File: pages/box-office/_performanceId/sell/complete.vue [hunk 5]
```diff
@@ -34,41 +58,96 @@ export default {
...
+              }),
+            },
+          },
+          'checkInBooking'
+        )
+        this.checkedIn = true
+        let message = 'Tickets checked in'
+        if (this.autoCheckIn) {
+          message = 'Tickets automatically checked in'
+        }
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:111]:
```suggestion
        let message = this.autoCheckIn ? 'Tickets automatically checked in' : 'Tickets checked in'
```

Could move inline to line 114 if you wanted

File: pages/box-office/_performanceId/sell/complete.vue [hunk 6]
```diff
@@ -34,41 +58,96 @@ export default {
...
+              reference: this.booking.reference,
+              performanceId: this.booking.performance.id,
+              tickets: this.booking.tickets.map((ticket) => {
+                return {
+                  ticketId: ticket.id,
+                }
+              }),
+            },
+          },
+          'unCheckInBooking'
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:138]: See https://github.com/BristolSTA/uobtheatre-web/blob/develop/graphql/mutations/box-office/UnCheckInTickets.gql#L7: the name of the mutation is `uncheckInBooking`. This is probably why you get that error

File: pages/box-office/_performanceId/sell/complete.vue (hunk 2 above)
Comment (atoff) [reply pages/box-office/_performanceId/sell/complete.vue:150]: See above comment :)

File: pages/box-office/_performanceId/sell/complete.vue [hunk 7]
```diff
@@ -34,41 +58,96 @@ export default {
...
-      })
-    }
+    if (this.autoCheckIn) this.checkInTickets()
   },
   beforeDestroy() {
     // Remove stored booking ID
     this.$store.commit('box-office/SET_IN_PROGRESS_BOOKING_ID', null)
   },
   methods: {
+    async checkInTickets() {
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:89]: Is there a way we could merge `checkInTickets()` and `unCheckInTickets()` together?

I'm thinking with could supply an argument like `checkIn` as a boolean to a function called `changeTicketsStatus()` or something to decide which operation to do, and then use this to choose the corresponding mutation and messages?

I think this would be neater than having two blocks of basically identical code, but up for your opinion?

**Review by atoff — CHANGES_REQUESTED** [review]

File: pages/box-office/_performanceId/sell/complete.vue (hunk 5 above)
Comment (streth11) [reply pages/box-office/_performanceId/sell/complete.vue:111]: tried it and swal didnt print the evaluation of the function

File: pages/box-office/_performanceId/sell/complete.vue [hunk 8]
```diff
@@ -34,41 +60,74 @@ export default {
...
+        ? 'Tickets automatically checked in'
+        : 'Tickets checked in'
+      let errMessage = 'Unable to check in tickets'
+
+      if (!checkingIn) {
+        checkInMutationGQL = UnCheckInTickets
+        checkInMutationName = 'uncheckInBooking'
+        sucsessMessage = 'Tickets un-checked in'
+        errMessage = 'Unable to un-check in tickets'
+      }
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:100]:
```suggestion
      let mutationGql = checkingIn ? CheckInTickets : UnCheckInTickets
      let mutationName = checkingIn ? 'checkInBooking' : 'uncheckInBooking'
      let sucsessMessage = this.autoCheckIn
        ? 'Tickets automatically checked in'
        : checkingIn  ? 'Tickets checked in' : 'Tickets un-checked in'
      let errMessage =  checkingIn ? 'Unable to check in tickets' : 'Unable to un-check in tickets'
```

File: pages/box-office/_performanceId/sell/complete.vue [hunk 9]
```diff
@@ -34,41 +60,74 @@ export default {
...
-      successToast.fire({
-        timer: 4000,
-        title: 'Tickets automatically checked in',
-      })
-    } catch (e) {
-      errorToast.fire({
-        title: 'Unable to check in tickets automatically',
-      })
-    }
+    if (this.canAutoCheckIn) this.changeTicketStatus(true)
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:72]: 98% sure that this needs to be `this.canAutoCheckIn()` (i.e. with brackets) to execute the function. Same on line 80

File: pages/box-office/_performanceId/sell/complete.vue (hunk 8 above)
Comment (atoff) [reply pages/box-office/_performanceId/sell/complete.vue:100]: Should also be able to move these variables in line now (i.e. where they are used)

**Review by atoff — CHANGES_REQUESTED** [review]

**Review by atoff — APPROVED** [review]

File: pages/box-office/_performanceId/sell/complete.vue [hunk 10]
```diff
@@ -34,41 +60,66 @@ export default {
...
     // Remove stored booking ID
     this.$store.commit('box-office/SET_IN_PROGRESS_BOOKING_ID', null)
   },
   methods: {
+    canAutoCheckIn() {
+      return this.performanceDoorsDiffMinutes() <= 15
+    },
+    performanceDoorsDiffMinutes() {
+      return (
+        (Date.parse(this.booking.performance.doorsOpen) - new Date()) / 60000
```
Comment (atoff) [inline pages/box-office/_performanceId/sell/complete.vue:84]:
```suggestion
        DateTime.fromISO(this.booking.performance.doorsOpen).diff(DateTime.now()).as('minutes')
```

**Review by atoff — APPROVED** [review]
